defaults:
  - _self_
  - submitit
  - override hydra/launcher: submitit_slurm

IC_Test:
  t_range: [0, 10]

  n_points: 100
  repeats: 100
  noise_std_dev: 2.0
  noise_percentage: null
  vector_field: s1
  true_args: [-0.3, -2.0]
  true_x0: null
  upper_x0: [5.0, 0.0]

  lower_x0: [5.0, 0.0]

  x0_n_points: 1

  # ed: [25, 51, 74,  1,  2,  3,  5, 16, 99,  4, 15,  6, 18,  7, 23,  1, 16,
  #      3,  5, 13,  8, 35,  9, 41,  1, 20,  3, 94, 35, 18] # 30 sigma=2 lam=0.001

  ed: [24,  1, 48, 12,  2, 73, 19, 98,  3,  9, 31,  4,  8, 60, 16, 10, 83,
                40, 15,  7,  5, 11, 23, 17, 99, 14, 22, 18, 21, 38] # 30 sigma=2 lam=0.001

  no_ed: false
  random_ed: false

  w0: [-1.0, -1.0]

optimizer:
  learning_rate: 0.001
  max_steps: 10000

hydra:
  sweeper:
    params:
      IC_Test.no_ed: true, false 
      IC_Test.noise_std_dev: 1.0, 2.0, 3.0, 5.0

logging:
  mode: online
  project: ED Tests
  group: IC ED S1 Try 10 Noise MSE study - MLE at true args
  name: VField ${IC_Test.vector_field} Noise ${IC_Test.noise_std_dev} NO ED ${IC_Test.no_ed} Random ED ${IC_Test.random_ed}
  tags:
  - S1
  - W/O GPU