hydra:
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    timeout_min: 480  # 4 hours
    cpus_per_task: 1
    tasks_per_node: 1
    mem_per_cpu: 36000  # 8GB per CPU
    # gpus_per_node: 1
    nodes: 1
    name: "PlearnKoopman"
    array_parallelism: 270  # Number of jobs to run in parallel
    additional_parameters:
      # gres: "gpu:1,gpumem:16000"  # Include GPU memory here
      account: "ls_krausea"  # Account name
    comment: "PlearnKoopman jobs"
    setup: 
      - "export TF_CPP_MIN_LOG_LEVEL=0"
      - "export WANDB__SERVICE_WAIT=300"