Architecture:
  _target_: 'DynamicKoopman.PLearnKoop'
  _convert_: 'none'

Hyperparameters:

  latent_dim: 5

  encoder:

    type: MLP
    include_w: False
    params:
      layers: null
      activation: None
      scale: 0.1
      use_bias: False
      layer_norm: False

  decoder:

    type: MLP
    params:
      layers: null
      activation: None
      scale: 0.1
      use_bias: False
      layer_norm: False

  propagator:

    type: Continuous
    learn_koopman: False
    include_IC: False
    latent_dim: ${..latent_dim}

    encoder:

      type: MLP
      params:
        layers: null
        activation: None
        scale: 0.1
        use_bias: False
        layer_norm: True