Architecture:
  _convert_: 'all'
  _target_: 'Archs.PLearnKoopmanLipCK'

Hyperparameters:
  params_encoding: true
  IC_K: true
  mid_d: 1000
  latent_d: 20
  en: 2
  dn: 2
  pn: 2

  ff: False
  scale: 32



  
  