Architecture:
  _target_: 'Archs.PLearnKoopmanLipCL'
  _convert_: 'all'

Hyperparameters:
  params_encoding: true
  IC_K: false
  mid_d: 1000
  latent_d: 20
  en: 5
  dn: 5
  pn: 5

  ff: False
  scale: 32
  