Architecture:
  _target_: 'DynamicKoopman.PLearnKoop'
  _convert_: 'none'

Hyperparameters:

  latent_dim: 4

  encoder:

    type: LipMLP
    include_w: False
    params:
      layers: null
      activation: relu
      scale: 0.01
      use_bias: True
      layer_norm: False

  decoder:

    type: LipMLP
    params:
      layers: null
      activation: relu
      scale: 0.01
      use_bias: True
      layer_norm: False

  propagator:

    type: Continuous
    learn_koopman: False
    include_IC: True
    only_IC: True
    latent_dim: ${..latent_dim}

    encoder:

      type: MLP
      params:
        layers: null
        activation: relu
        scale: 0.1
        use_bias: True
        layer_norm: True